// utils/ErrorHandler.js

class PaymentError extends Error {
  constructor(message, code = 'UNKNOWN_ERROR', details = {}) {
    super(message);
    this.name = "PaymentError";
    this.code = code;
    this.details = details;
  }
}

const ERROR_CODES = {
  INITIALIZATION_ERROR: 'INITIALIZATION_ERROR',
  PAYMENT_CREATION_FAILED: 'PAYMENT_CREATION_FAILED',
  INVALID_ORDER_DETAILS: 'INVALID_ORDER_DETAILS',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_WEBHOOK_SIGNATURE: 'INVALID_WEBHOOK_SIGNATURE',
  MISSING_CUSTOMER_DETAILS: 'MISSING_CUSTOMER_DETAILS',
  INVALID_DATA: 'INVALID_DATA',
  DATABASE_INSERT_FAILED: 'DATABASE_INSERT_FAILED',
  SUPABASE_ERROR: 'SUPABASE_ERROR',
  WEBSOCKET_BROADCAST_ERROR: 'WEBSOCKET_BROADCAST_ERROR',
  CHAT_MESSAGE_FAILED: 'CHAT_MESSAGE_FAILED'
};

module.exports = {
  PaymentError,
  ERROR_CODES
};
